import { useMemo } from 'react';
import { Landmark, Download, CheckCircle2, AlertTriangle } from 'lucide-react';
import { GlassCard } from './GlassCard';
import { Button } from '@/components/ui/button';
import { structureGreenBond, GreenBondDeal } from '@/utils/structureGreenBond';

interface DealTicketCardProps {
  financialData: any | null;
  locationName: string | null;
}

const formatCurrency = (value: number) => {
  if (Math.abs(value) >= 1_000_000) return `$${(value / 1_000_000).toFixed(1)}M`;
  if (Math.abs(value) >= 1_000) return `$${(value / 1_000).toFixed(0)}K`;
  return `$${value.toFixed(0)}`;
};

export const DealTicketCard = ({ financialData, locationName }: DealTicketCardProps) => {
  const deal: GreenBondDeal | null = useMemo(() => {
    if (!financialData) return null;
    return structureGreenBond(financialData);
  }, [financialData]);

  const isBankable = deal
    ? deal.rating.startsWith('AAA') || deal.rating.startsWith('BBB')
    : false;

  const handleExport = () => {
    if (!deal) return;
    const lines = [
      '═══════════════════════════════════════',
      '       GREEN BOND TERM SHEET',
      '═══════════════════════════════════════',
      '',
      `Location:       ${locationName ?? 'N/A'}`,
      `Principal:      ${formatCurrency(deal.principal)}`,
      `Coupon Rate:    ${deal.coupon.toFixed(2)}%`,
      `Tenor:          ${deal.tenor} years`,
      `Credit Rating:  ${deal.rating}`,
      `Greenium:       ${formatCurrency(deal.greenium_savings)} (est. savings)`,
      '',
      `Bankability:    ${isBankable ? 'Bankable Deal' : 'Blended Finance Required'}`,
      '',
      '───────────────────────────────────────',
      `Generated by Resilient Climate Platform`,
      `Date: ${new Date().toISOString().split('T')[0]}`,
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `green-bond-term-sheet-${(locationName ?? 'deal').replace(/\s+/g, '-').toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!deal) {
    return (
      <GlassCard className="p-4 w-full">
        <div className="flex items-center gap-2 mb-3">
          <Landmark className="w-4 h-4 text-amber-400" />
          <h3 className="text-sm font-semibold text-white">Green Bond Term Sheet</h3>
        </div>
        <div className="p-6 rounded-xl bg-white/5 border border-white/10 text-center">
          <Landmark className="w-6 h-6 text-white/30 mx-auto mb-2" />
          <p className="text-xs text-white/50">
            Click a <span className="text-amber-400 font-medium">Global Atlas pin</span> to generate a deal ticket from its financial data.
          </p>
        </div>
      </GlassCard>
    );
  }

  return (
    <GlassCard className="p-4 w-full space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-base">🟩</span>
          <h3 className="text-sm font-semibold text-white">Green Bond Term Sheet</h3>
        </div>
        {/* Bankability Badge */}
        <div
          className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-semibold border ${
            isBankable
              ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30'
              : 'bg-amber-500/20 text-amber-400 border-amber-500/30'
          }`}
        >
          {isBankable ? (
            <>
              <CheckCircle2 className="w-3 h-3" />
              Bankable Deal
            </>
          ) : (
            <>
              <AlertTriangle className="w-3 h-3" />
              Blended Finance
            </>
          )}
        </div>
      </div>

      {/* Location */}
      {locationName && (
        <p className="text-[10px] text-white/50 -mt-1 pl-7">{locationName}</p>
      )}

      {/* Principal */}
      <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20">
        <span className="text-[10px] text-white/50 uppercase tracking-wider">Principal (CAPEX)</span>
        <div className="text-3xl font-bold text-amber-400 tabular-nums mt-0.5">
          {formatCurrency(deal.principal)}
        </div>
      </div>

      {/* Grid: Coupon, Tenor, Rating */}
      <div className="grid grid-cols-3 gap-2">
        <div className="p-3 rounded-xl bg-white/5 border border-white/10 text-center">
          <span className="text-[10px] text-white/50 block">Coupon</span>
          <span className="text-sm font-bold text-white tabular-nums">{deal.coupon.toFixed(2)}%</span>
        </div>
        <div className="p-3 rounded-xl bg-white/5 border border-white/10 text-center">
          <span className="text-[10px] text-white/50 block">Tenor</span>
          <span className="text-sm font-bold text-white tabular-nums">{deal.tenor}yr</span>
        </div>
        <div className="p-3 rounded-xl bg-white/5 border border-white/10 text-center">
          <span className="text-[10px] text-white/50 block">Rating</span>
          <span className="text-[10px] font-bold text-white leading-tight">{deal.rating.split(' ')[0]}</span>
          <span className="text-[8px] text-white/40 block">{deal.rating.match(/\(.*\)/)?.[0]}</span>
        </div>
      </div>

      {/* Greenium */}
      <div className="p-3 rounded-xl bg-white/5 border border-white/10 flex items-center justify-between">
        <span className="text-xs text-white/60">Greenium Savings (est.)</span>
        <span className="text-sm font-bold text-emerald-400">{formatCurrency(deal.greenium_savings)}</span>
      </div>

      {/* Export */}
      <Button
        onClick={handleExport}
        className="w-full h-10 text-xs font-semibold bg-gradient-to-r from-amber-600/80 to-yellow-600/80 hover:from-amber-600 hover:to-yellow-600 rounded-xl border border-amber-500/30 shadow-[0_0_15px_rgba(245,158,11,0.2)] hover:shadow-[0_0_25px_rgba(245,158,11,0.4)] transition-all text-white"
      >
        <Download className="w-4 h-4 mr-2" />
        Export Prospectus (Term Sheet)
      </Button>
    </GlassCard>
  );
};
